# Generated by Django 5.1.2 on 2025-03-06 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0002_votes"),
        ("track", "0003_room_current_song"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Votes",
            new_name="Vote",
        ),
    ]
